language: python
python:
  - '3.7'
  - '3.8'
before_install:
  - pip install poetry
  - nvm install
  - nvm use
  - npm install -g yarn
install:
  - poetry install
  - yarn install --dev
script:
  - yarn run ts
  - yarn run scss
  - yarn run tslint
  - poetry run pytest
  - yarn run test
