language: python
python: 
  - '3.8'
before_install:
  - pip install poetry
  - nvm use --lts
  - npm install -g yarn
install:
  - poetry install
script:
  - poetry run pytest
  - yarn run ts
  - yarn run scss
  - yarn run tslint
