---
- hosts: bots
  tasks:
    - name: Install system packages
      apt:
        pkg:
          - nginx-full
          - supervisor
          - python3.6
        update_cache: yes
        cache_valid_time: 300
        state: latest
      become: true

    - name: Perform a OS update
      apt:
        upgrade: dist
        update_cache: yes
        cache_valid_time: 300
      become: true

    - name: Clean up unneeded packages
      apt:
        autoremove: yes
      become: true

    - name: Clean up the APT cache
      apt:
        autoclean: yes
      become: true
